variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_GRACE_CACHE_DIR: "$CI_PROJECT_DIR/.cache/python-grace"
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache

lint:
  image: python:3.9
  before_script:
    - pip install gitlint pre-commit
  script:
    - gitlint
    - pre-commit run --all-files

test:
  parallel:
    matrix:
      - IMAGE:
        - python:3.6
        - python:3.7
        - python:3.8
        - python:3.9
  image: $IMAGE
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gfortran libmotif-dev
    - pip install poetry
    - poetry install --no-root
  script:
    - poetry install
    - poetry run pytest

test-install:
  extends: test
  script:
    - poetry install
    - mkdir testdir
    - cd testdir
    - poetry run grace template sm/eewwa
    - poetry run grace grc
    - poetry run grace grcfort
    - make all
    - ./gauge
    - ./integ
    - ./spring
