repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        additional_dependencies: [pyyaml==6.0]
    -   id: cmake-lint
        additional_dependencies: [pyyaml==6.0]

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
    -   id: editorconfig-checker
        exclude: CMakeLists.txt|\.cmake

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
    -   id: editorconfig-checker
        name: editorconfig-checker (CMake)
        files: CMakeLists.txt|\.cmake
        args: [-disable-indentation]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        entry: pflake8
        additional_dependencies:
        -   flake8-bandit==4.1.1
        -   flake8-bugbear==23.2.13
        -   flake8-builtins==2.1.0
        -   flake8-comprehensions==3.10.1
        -   flake8-docstrings==1.7.0
        -   flake8-pytest-style==1.7.2
        -   pep8-naming==0.13.3
        -   pyproject-flake8==6.0.0  # frozen for flake8 6.0.0

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   click==8.0.4  # frozen for python 3.6
        -   pytest==7.0.1  # frozen for python 3.6

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
    -   id: gitlint
