name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * * # monthly

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: 3.6
            cc: gcc-10
            fc: gfortran-10
          - os: ubuntu-20.04
            python-version: 3.7
            cc: gcc-10
            fc: gfortran-10
          - os: ubuntu-20.04
            python-version: 3.8
            cc: gcc-10
            fc: gfortran-10
          - os: ubuntu-20.04
            python-version: 3.9
            cc: gcc-10
            fc: gfortran-10
          - os: ubuntu-20.04
            python-version: "3.10"
            cc: gcc-10
            fc: gfortran-10
          - os: ubuntu-20.04
            python-version: 3.9
            cc: gcc-8
            fc: gfortran-8
          - os: ubuntu-20.04
            python-version: 3.9
            cc: gcc-9
            fc: gfortran-9
          - os: macos-11
            python-version: 3.9
            cc: gcc-11
            fc: gfortran-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache for pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Cache for GRACE
        uses: actions/cache@v2
        with:
          path: ~/.cache/python-grace
          key: python-grace-221.2006.0116
          restore-keys: |
            python-grace-

      - name: Install dependencies (apt)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          [ ${{ matrix.cc }} = gcc-8 ] && sudo apt-get install -y -qq g++-8
          [ ${{ matrix.fc }} = gfortran-8 ] && sudo apt-get install -y -qq gfortran-8
          sudo apt-get install -y -qq libmotif-dev

      - name: Install dependencies (pip)
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run tests
        run: tox -vvv
        env:
          CC: ${{ matrix.cc }}
          FC: ${{ matrix.fc }}
